name: Build and push Osiguranje-Frontend to GHCR

on:
  push:
    branches:
      - master

concurrency: ci-${{ github.ref }}

jobs:
  docker-build-push:
    name: Build and push Osiguranje-Frontend to GHCR
    runs-on: ubuntu-latest

  permissions:
    contents: read
    packages: write
    id-token: write
  
  steps:
    - uses: actions/checkout@master
      with:
        fetch-depth: 1

    - name: Set up QEMU
      uses: actions/setup-qemu-action@v1

    - name: Set up Docker buildx
      uses: docker/setup-buildx-action@v1

    - name: Login to GHCR
      uses: docker/login-action@v1
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Build and push image
      uses: docker/build-push-action@v2
      with:
        platforms: linux/amd64
        push: true
        tags: ghcr.io/raf-si-2021/osiguranje-frontend:latest